// <auto-generated />
namespace Reuse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class imagens_videos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imagens_videos));
        
        string IMigrationMetadata.Id
        {
            get { return "201510112141315_imagens_videos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
