// <auto-generated />
namespace Reuse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class images_usuarios3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(images_usuarios3));
        
        string IMigrationMetadata.Id
        {
            get { return "201510122051377_images_usuarios3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
